/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import javax.swing.JOptionPane;

/**
 *
 * @author Akito
 */
public class penarikan extends javax.swing.JFrame {
saldo info;
tarik abm;
int saldo;
int sala;
int t;
    /**
     * Creates new form penarikan
     */
    public penarikan(int saldo) {
        
        
        this.saldo = saldo;
        abm = new tarik();
     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setText("Pilih Nominal Penarikan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 80, 310, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/btn.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 30, 216, 47);

        jButton1.setText("50000");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 150, 130, 40);

        jButton2.setText("100000");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 150, 130, 40);

        jButton4.setText("500000");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(210, 200, 130, 40);

        jButton5.setText("2000000");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(210, 250, 130, 40);

        jButton7.setText("200000");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 200, 130, 40);

        jButton6.setText("1000000");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(60, 250, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 350);

        setBounds(0, 0, 416, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        abm.ambil(50000 , saldo);
        this.saldo = abm.getsaldo();
        
        int z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BTN", JOptionPane.YES_NO_OPTION, 3);
        if (z == 0)
        {
            new index(this.saldo).setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BTN ,silahkan ambil kartu ATM Anda.");
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        abm.ambil(200000, saldo);
        this.saldo = abm.getsaldo();
        int z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BTN", JOptionPane.YES_NO_OPTION, 3);
        if (z == 0)
        {
            new index(this.saldo).setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BTN ,silahkan ambil kartu ATM Anda.");
            dispose();
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        abm.ambil(100000 ,saldo);
        this.saldo = abm.getsaldo();
        int z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BTN", JOptionPane.YES_NO_OPTION, 3);
        if (z == 0)
        {
            new index(this.saldo).setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BTN ,silahkan ambil kartu ATM Anda.");
            dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        abm.ambil(500000 , saldo);
        this.saldo = abm.getsaldo();
        int z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BTN", JOptionPane.YES_NO_OPTION, 3);
        if (z == 0)
        {
            new index(this.saldo).setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BTN ,silahkan ambil kartu ATM Anda.");
            dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        abm.ambil(2000000,saldo);
        this.saldo = abm.getsaldo();
        int z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BTN", JOptionPane.YES_NO_OPTION, 3);
        if (z == 0)
        {
            new index(this.saldo).setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BTN ,silahkan ambil kartu ATM Anda.");
            dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        abm.ambil(1000000,saldo);
        this.saldo = abm.getsaldo();
        int z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BTN", JOptionPane.YES_NO_OPTION, 3);
        if (z == 0)
        {
            new index(this.saldo).setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BTN ,silahkan ambil kartu ATM Anda.");
            dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
